### ISSUE TITLE
[Suggestion] The inbox button is useful and should not be hidden

### ISSUE THREAD

**Issue by 6stR2** [DapperCore/NordCord#2]
The inbox button on the top toolbar is hidden by this line [here](https://github.com/DapperCore/NordCord/blob/00a8c419cc014484d548a616e9074d505512b76e/index.css#L164)
It is a QoL kind of thing and there is no reason to hide it.

**Comment by DapperCore** [comment]
I personally don't make use of the inbox button at all, which is why I removed it. However, you're free to modify the css however much you desire to suit your own use case!
